name: Java CI with Maven

on:
  push:
    branches: [ master ]  # Trigger workflow on push events to the 'master' branch

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code  # Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK  # Set up Java Development Kit (JDK)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the desired Java version (e.g., Java 11)

    - name: Build with Maven  # Build the Maven project
      run: mvn clean package -DskipTests=true --file pom.xml  # Use 'clean' and 'package' goals, skip tests, specify 'pom.xml' file

    - name: Run tests  # (Optional) Run any tests after building
      run: mvn test  # Execute Maven tests
