name: Java CI with Maven

on: 
  push:
    branches: [ master ]  # Trigger workflow on push events to the 'master' branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package --file pom.xml -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 -Dmaven.test.skip=true -Dmaven.source.path=src/FileSyncCommand

    - name: Debug output
      run: |
        ls -l    # List all files in the current directory
        ls -l target/   # List files in the 'target' directory

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-artifact
        path: target/first-demo-project1-0.0.1-SNAPSHOT.jar  # Update with the correct JAR file path
