name: Java CI with Maven

on:
  push:
    branches: [ main ]  # Trigger workflow on push events to the 'main' branch

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - uses: actions/checkout@v2  # Checkout the repository

    - name: Set up JDK  # Set up Java Development Kit (JDK)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the desired Java version (e.g., Java 11)

    - name: Build with Maven  # Build the Maven project
      run: mvn -B package --file pom.xml

    - name: Run tests  # (Optional) Run any tests after building
      run: mvn test
